### ISSUE TITLE
Warn users when facet data doesn't match mark data

### ISSUE THREAD

**Issue by mkfreeman** [observablehq/plot#1009]
Provide a visual warning to users when they specify facet data that doesn't match the mark data. This is especially tricky in the case when the facet and mark data both use the same `.filter()` function, for example  ([notebook here](https://observablehq.com/d/a869f84e397d44b7)):
```js
Plot.plot({
  facet: {
    data: aapl.filter(d => d.Close > 1),
    y: d => d3.utcFormat("%Y")(d.Date)
  },
  marks: [
    Plot.lineY(aapl.filter(d => d.Close > 1), {x: "Date", y: "Close"})
  ]
})
```

The logic I would imagine is:

If there is facet data and there is mark data AND the mark data is not strictly equal to `===` the facet data, provide a warning like _Facet data and mark data must be strictly equal for accurate faceting_

**Comment by mbostock** [comment]
Related #755.

I don’t think we should do this as stated because it will trigger on something like `Plot.ruleX([0])` (where `[0]` is the mark data, which cannot match the facet data).

We could maybe have a warning if the mark data’s length is equal (exactly?) to the facet data length, but the two data are not the same object, and maybe when the data length is also 10 (?) or greater to avoid false positives.

(I also don’t think we should try to target the _array_.filter case exactly, because you can also get into this situation with duplicate _array_.map calls, for example.)

**Comment by Fil** [comment]
When the two lengths are equal we should furthermore check that the contents are equal with` facet.data.every((d, i) => d === mark.data[i])`

I was also thinking to do the check at the level of *facet* rather than on each mark, so that if a facet is required and no mark has a defined facet option and one mark has a data of the same length and it is contents-equal to the facet data…

**Comment by mbostock** [comment]
> When the two lengths are equal we should furthermore check that the contents are equal with facet.data.every((d, i) => d === mark.data[i])

I disagree. This is what I was alluding to with this comment: 

> (I also don’t think we should try to target the array.filter case exactly, because you can also get into this situation with duplicate array.map calls, for example.)

I think the warning should apply to any case where the data is _likely_ be faceted, regardless of whether that data is identical to the facet data. Hence only the length check and ignoring the contents.
