### ISSUE TITLE
field dsl?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1011]
Things like these would be useful in the field() function:
* `""`: d => d
* `"(:name)"`: d => autoType(d["name"])
* `"(+name)"`: d => +d["name"]
* `"(:name as %Y/%m)"`: d => d3.utcParse(…, (d["name"]))
* `"(name!)"`: d => autoType(d.?["name"])

Let's keep in mind that we'd want this function to live in D3 too.

**Comment by mbostock** [comment]
I am opposed to adding a string-based DSL with very limited exceptions (such as `"p80"` for 80th percentile like we do for reducers). I see a DSL as: having limited value on top of writing a function accessor; going against the parsimony principle (there should ideally be only one method of accomplishing a task, but if there are multiple, the preferred method should be obvious); being nonstandard/proprietary (a new Plot-specific thing for people to learn instead of using standard JavaScript). I recommend we close this issue.
