### ISSUE TITLE
cuve attribute is ignored if line marks have a title

### ISSUE THREAD

**Issue by nobarany** [observablehq/plot#1097]
For example the curve is ignored in the code below:
```  
Plot.plot({
    width: 500,
    marks: [
      Plot.line(
        [
          { t: 10, val: 200 },
          { t: 30, val: 300 },
          { t: 100, val: 200 },
        ],
        {
          x: 't',
          y: 'val',
          curve: 'natural',
          title: d => d.val,
        }
      ),
    ],
  });
```

Removing the title attribute would revive the curve behavior. 

Please let me know if there's a workaround.

**Comment by mbostock** [comment]
This is the expected behavior and it’s because your title varies with each data point, causing the line to be broken up into segments. This in turn affects the behavior of interpolation for certain curves that need more than two control points. If you still want the title, you might consider using a dot mark as an overlay on top of the line, perhaps even an invisible (transparent) dot if you don’t want the dots to be visible. Note however that not all curves guarantee that the lines go through the control points.

**Comment by nobarany** [comment]
Makes sense, thank you! It'd be great to add a console warning to notify the developer that the curve attribute is being ignored because of the title.
