### ISSUE TITLE
heatmap mark?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1122]
I sometimes see users trying to make heatmaps with Plot.cell, which results in incorrect charts when x and y are continuous. The recommended approach (until now) was to use Plot.bin to create the small squares (or rather, rectangles), as x/y bins. However with projections, this is now incomplete, and we should have a solution for heatmaps in the projected space. Like hexbin, but based on squares (or any other tessellation?). There's probably a lot of code to share with hexbin, the most difficult part to decide might be the API?

**Comment by mbostock** [comment]
I would like to better understand how continuous heatmaps are commonly expressed. Do we want a sparse sample-based approach as with the pixel mark in #1185 (which is really just an optimization of the existing rect mark + interval transform)? Or does the user want to supply a continuous function of *xy* that is them sampled automatically (in a grid) by Plot? Or maybe the user supplies dense samples in a grid (similar to ImageData) so that the *x* and *y* channels can be implicit? Or all of the above?

**Comment by Fil** [comment]
matplotlib has a funky interpolation method
https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html

**Comment by mbostock** [comment]
Fixed in #1196.
