### ISSUE TITLE
Plot.link, arrow, rect projection support

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1126]
Probably the only thing missing is to do X1, X2, Y1, Y2 in https://github.com/observablehq/plot/blob/695248578d442ad084220b50f9dc239f0edbd032/src/projection.js#L113 ?

(not urgent)

**Comment by mbostock** [comment]
The challenge is ambiguity around which points are being projected. The link mark seems easy because [x1, y1] and [x2, y2] represent two points with four channels. (It would also work for the arrow mark for the same reason.) But for the rect mark the same four channels mean _four_ points: [x1, y1], [x1, y2], [x2, y1], and [x2, y2]. And we don’t have a way to represent four points in four channels. It would work fine for cylindrical projections, at least… so maybe it’s fine to just do this behavior universally for marks that use x1, y1, x2, y2? Though we’d also want to think through rules and areas too… Tricky!
