### ISSUE TITLE
png/svg download to include legend?

### ISSUE THREAD

**Issue by ijlyttle** [observablehq/plot#1286]
I don't know if this is a `Plot` question or an `observablehq.com` question, but I thought I'd start here.
 
On any of the charts with legends here: https://observablehq.com/@observablehq/plot-legends, if I click "Download PNG" or "Download SVG", I get an image of the chart that does not include the legend. I imagine this follows from the legend being an add-on to the chart. 

Could there be a convenient way to get them both in an image download?

Thanks!

**Comment by Fil** [comment]
It's mostly an observablehq question, but it's also a Plot question, since Plot returns an HTML figure. Either way we'll need to find a good solution!

For PNG downloads, I've started experimenting with the image-to-html library here: https://observablehq.com/@fil/hello-html-to-image
One could also try with html2canvas https://observablehq.com/@fil/hello-html2canvas

For SVG, I haven't found how to generically convert HTML to SVG, but I have a _heap of code_ that 99% works charts. https://observablehq.com/@fil/plot-figure-to-svg

**Comment by mbostock** [comment]
Please file this in the Observable feedback repository:

https://github.com/observablehq/feedback

I would transfer it but for some reason GitHub isn’t letting me.
