### ISSUE TITLE
Max fillOpacity is replaced with 1

### ISSUE THREAD

**Issue by nobarany** [observablehq/plot#1307]
When fillOpacity is a function or property, the maximum value is replaced with 1. For example:
```
...
// fillOpacity: 0.2 works fine
fillOpacity: d => 0.2
...
```
results in `fill-opacity="1"`

**Comment by mbostock** [comment]
Yep, that’s because when you specify the fill opacity as a function, you are supplying _abstract_ rather than _literal_ values. For example, 0.2 might represent kilometers or degrees Kelvin. If you want Plot to interpret the fill opacity literally, you need to set the type of the _opacity_ scale to linear:

```js
Plot.plot({
  opacity: {type: "identity"},
  marks: […]
})
```

Alternatively, as of Plot 0.6.4 (which is released to npm but FYI is not yet the default on Observable), you can opt-out on a specific channel:

```js
Plot.dot(data, {…, fillOpacity: {value: (d) => 0.2, scale: null}}
```

We could perhaps add some value inference if all values for a channel bound to the _opacity_ scale are in the range [0, 1]; we do something similar for channels bound to the _color_ and _symbol_ scale. I’ll file a separate feature request for that.

**Comment by nobarany** [comment]
Oh, great, thanks! I'm using an explicit scale, so, `scale:null` fixed it.
