### ISSUE TITLE
Upgrading from 0.6.1 to 0.6.2 seems to have broken (or changed in unexpected way) date handling

### ISSUE THREAD

**Issue by nobarany** [observablehq/plot#1311]
Upgrading from 0.6.1 to 0.6.2 seems to have broken something related to date handling. The chart bellow that has the 2023 data is the original one, and after the upgrade all the 2023 data is not shown.
---update---
replaced the screenshots with [this notebook](https://observablehq.com/d/3f8b7073939abb34):

**Comment by mbostock** [comment]
Can you share your data and code to reproduce this example? Otherwise there’s not really anything to go on and we can’t investigate. Thank you.

**Comment by mbostock** [comment]
This is probably related to changes in the bin transform #1225, but I can’t speculate further without knowing either the data or the code.

**Comment by nobarany** [comment]
Right, here's the simplified of the code
```
  chart = Plot.plot({
    y: {
      grid: true,
      zero: true,
    },
    x: {
      type: 'utc',
      label: null,
    },
    marks: [
      Plot.rectY(
        rows,
        Plot.binX(
          { y: 'sum' },
          {
            x: xProp,
            y: yProp,
            thresholds: [4, 3, 2, 1, 0].map(q =>
              startOfQuarter(currentQuarter() - q)
            ),
            fill: (d: { special: boolean }) =>
              d.special ? '#ccc' : 'blue',
            inset: 1,
          }
        )
      ),
    ],
  });
```

**Comment by mbostock** [comment]
Can you share the data please too?

**Comment by mbostock** [comment]
And the rest of the code? A link to a working notebook would be best. Thanks.

**Comment by nobarany** [comment]
Ok, [here's the notebook](https://observablehq.com/d/3f8b7073939abb34). This helped me fix it. The data after the last threshold is not shown. so adding another threshold is a workaround. (the fix is commented out in the notebook)

**Comment by mbostock** [comment]
Here is a [minimal reproduction](https://observablehq.com/d/727cec8ecc4b8dfd):

```js
Plot.plot({
  y: { grid: true },
  marks: [
    Plot.rectY(
      [
        [3, 1],
        [4, 1],
        [5, 2],
        [6, 3],
        [7, 4],
        [8, 5],
        [9, 4],
        [10, 3],
        [11, 2],
        [12, 1],
        [13, 1],
        [14, 2],
        [15, 3]
      ],
      Plot.binX(
        { y: "sum" },
        { x: ([x]) => x, y: ([, y]) => y, thresholds: [1, 4, 7, 10, 13] }
      )
    )
  ]
})
```

In 0.6.1 this renders as:

![untitled (15)](https://user-images.githubusercontent.com/230541/222834845-a6e3dd95-4365-4546-84e2-5340eb65599c.png)

In 0.6.2 and later this renders as:

![untitled (16)](https://user-images.githubusercontent.com/230541/222834864-e326a816-8117-47e5-a78b-2de0398fc3b8.png)

**Comment by mbostock** [comment]
In the old behavior, the first bin starts at the lowest _x_ value in the data (3) rather than the lowest threshold (1). And likewise the last bin ends at the highest _x_ value in the data (15) rather than the highest threshold (13); an extra bin covers the range beyond the last threshold (13–15).

Whereas in the new behavior, _n_ thresholds specify _n_ - 1 bins. Values below the lowest threshold or above or equal to the highest threshold are effectively discarded.

I think the new behavior is what we want. However the README describes the opposite behavior, where _n_ thresholds specify _n_ + 1 bins. We should fix this.

A problem with the old behavior is that the extreme bins can have an irregular width. And it’s not possible to “nice” these extreme bins because we shouldn’t assume that when arbitrary thresholds are provided that these thresholds are uniformly spaced; for example when using a UTC scale, months have different lengths. In the worst case, the extreme bins can have zero width be invisible. There’s a history of these fiddly issues with binning:

* https://github.com/d3/d3-array/pull/177
* https://github.com/d3/d3-array/pull/65

Glad you were able to fix this. And thank you for the report!

**Comment by nobarany** [comment]
In practice either behavior is perfectly fine, but in terms of ease of reasoning, seems to me that one threshold should be able to break a space into two.

**Comment by mbostock** [comment]
FWIW The idiomatic recommendation for your case is `thresholds: d3.utcMonth.every(3)`, which is much simpler than calculating the thresholds by hand. And since #1205 we could add `thresholds: "quarter"` to make this even simpler.

**Comment by nobarany** [comment]
great, thanks!
