### ISSUE TITLE
Auto mark: no display with non-zero reducer and bar mark

### ISSUE THREAD

**Issue by tophtucker** [observablehq/plot#1340]
[See examples](https://observablehq.com/d/02b8ff51e7cf1c33). You get a bunch of zero-height bars:

<img src="https://user-images.githubusercontent.com/841829/225201341-83fed53e-7b6b-49a6-9c95-fb8d182102f8.png" width="640" />  

```
Plot.auto(olympians, {x: "date_of_birth", y: { value: "height", reduce: "mean" }, mark: "bar"}).plot()
```

The easy fix is to change the last row of this to use rectY instead of rect, on the theory that Plot.auto never has enough information to use Plot.rect effectively:

https://github.com/observablehq/plot/blob/c4892908a75c8b85abdd11475539c41d17b80962/src/marks/auto.js#L159-L174

That works in this case:

<img src="https://user-images.githubusercontent.com/841829/225201687-0f6e64f1-f6cb-4581-b9ea-7305380c138a.png" width="640" />

But it breaks the heatmap, because it gives it a zero baseline:

<img src="https://user-images.githubusercontent.com/841829/225201810-ebe3cd7b-dc19-4061-808e-bf65a27300da.png" width="640" />

```
Plot.auto(penguins, {x: "culmen_length_mm", y: "body_mass_g", color: "count"}).plot()
```

Because we're inferring whether to show the zero baseline from the mark type:

https://github.com/observablehq/plot/blob/c4892908a75c8b85abdd11475539c41d17b80962/src/marks/auto.js#L217-L220

We could change that bit. But, moreover, the heatmap example shows that Plot.auto _does_ sometimes have enough information to specify a rect mark: in the case of 2D binning. So just switching rect to rectY feels wrong.

**Comment by mbostock** [comment]
The mark-based zero check is also forgetting about rule. This should have a y = 0 rule like rect does.

![untitled (25)](https://user-images.githubusercontent.com/230541/225204706-200d217f-de05-4040-8b6d-34dc96d5e6b9.png)

```js
Plot.auto(olympians, {x: "date_of_birth", y: {value: "height", reduce: "mean"}, mark: "rule"}).plot()
```

**Comment by tophtucker** [comment]
@mbostock Can you think of a test case where using rect instead of rectY would break aside from the zero-baseline issue? These look identical:

```js
Plot.rect(penguins, Plot.bin({fill: "count"}, {x: "culmen_length_mm", y: "body_mass_g"})).plot()
Plot.rectY(penguins, Plot.bin({fill: "count"}, {x: "culmen_length_mm", y: "body_mass_g"})).plot()
```

**Comment by mbostock** [comment]
The only difference between rect and rectY is that rectY gives you an implicit stackY transform and defaults _y_ to the identity transform. So, if you’re supply _y1_ and _y2_ anyway, which the bin transform will do, there is no difference between rect and rectY. So I think it will be acceptable to use rectY here.

Regarding the zero baseline issue, maybe the answer is to address the TODO to move the zero-ness determination into autoSpec, rather than splitting the defaults into two places. You’ll have to rewrite the logic to be based more on “first principles” than the concrete mark type, but that might end up being a cleaner expression of the desired logic besides.
