### ISSUE TITLE
autoSpec should never return undefined for {color: {color}}

### ISSUE THREAD

**Issue by tophtucker** [observablehq/plot#1400]
Noticed while working on https://github.com/observablehq/plot/pull/1385 — this is, I think, the last undefined that autoSpec is returning:

https://github.com/observablehq/plot/blob/02731fb97277442120cb0d64350e60e6665c2ad1/src/marks/auto.js#L195-L199

**Comment by mbostock** [comment]
I’m not following this comment. It looks to me that the code can never return color: {color: undefined} because of the `colorColor !== undefined` check? So the type is

```ts
type AutoColorMaterializedOptions =
  | {value: ChannelValue | null; reduce: ChannelReduce | null}
  | {value: null; reduce: null; color: string};
```

which seems correct to me. We don’t want to say `color: null` when there’s a value or reduce because that would mean setting a constant color of none.

**Comment by tophtucker** [comment]
Oh! Sorry, I filed this hastily; I meant that the color property might not be in the returned object, not that it might be present and undefined (`color?: string`, not `color: string | undefined`). If that union type seems fine to you, then it’s fine with me. It felt weird that we’re not returning a fixed shape, but I hadn’t thought through what setting `color: null` would actually do, so, forget it! 😅
