### ISSUE TITLE
Convex hull mark?

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#154]

**Comment by Fil** [comment]
A plot plugin that implements a convex hull: https://observablehq.com/@fil/convex-hull-mark

The hull is computed in screen space, not data space, which is probably what we want in any case.

**Comment by Fil** [comment]
Related: #812 (since d3.Delaunay computes the hull).
We could also do an **ellipse** (i.e. the smallest ellipse containing the data).

Both of these can be done in data space (as transforms); contrast with Delaunay and Voronoi, which should be done as layouts/initializers (#801), since the x and y dimensions are not separable.

**Comment by mbostock** [comment]
Implemented in #917.
