### ISSUE TITLE
Plot.windowY doesn't work with shorthand

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1544]
With `data = Array.from({length: 100}, Math.random)`,  `Plot.lineY(data, Plot.windowY(7))` currently ignores the window transform, and we need an explicit form `Plot.lineY(data, Plot.windowY(7, {y: Plot.identity}))` instead. Might be possible to infer that it's a shorthand mark?

**Comment by mbostock** [comment]
Hmm, that’s tricky because the mapX/mapY transform doesn’t know what shorthand the downstream mark uses. But we could perhaps have the mapX transform default **x** to identity, and likewise the mapY transform default **y** to identity; I think that would handle the common case and work better than mapX/mapY having no effect.
