### ISSUE TITLE
Easier tree label positioning?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#1589]
In https://observablehq.com/@observablehq/plot-tree-tidy if you want to vary the orientation of node labels (so that leaves point to the right and parent nodes to the left, as in https://observablehq.com/@d3/tree), you can do:

```
Plot.plot({
  axis: null,
  margin: 10,
  marginLeft: 40,
  marginRight: 160,
  width: 928,
  height: 1800,
  marks: [
    Plot.tree(flare, {
      path: "name",
      delimiter: ".",
      dx: -6,
      textAnchor: "end",
      fontSize: { node: (d) => (d.children ? 10 : NaN) }
    }),
    Plot.text(flare, Plot.treeNode({
      path: "name",
      delimiter: ".",
      dx: 6,
      text: "node:name",
      fontSize: { node: (d) => (d.children ? NaN : 10) }
    }))
  ]
})
```

This could be easier if dx and textAnchor were channels (#1528, #909), or maybe we need a specific option to Plot.tree.

**Comment by mbostock** [comment]
The tree mark could do this automatically by generating separate text marks for internal _vs._ leaf nodes with appropriate filters. I don’t think we should make **dx** and **textAnchor** into channels; I appreciate that there is desire for it but making everything a channel makes it harder to implement marks and is not practical. It is better to focus our efforts on channels that are intended to encode data rather than allow bespoke formatting.

**Comment by Fil** [comment]
Would this be a new option (say, balancedLabels), or are you suggesting that we modify Plot.tree to do it by default? In that case would we just use dx and -dx?

**Comment by mbostock** [comment]
I think we would just modify tree to do this. Not configurable.
