### ISSUE TITLE
Opt-in to the color scale if values are in the domain, even if valid CSS colors?

### ISSUE THREAD

**Issue by jheer** [observablehq/plot#1593]
Consider the following Plot spec, with a hardwired domain and range for the color scale, and a filtered data set. Instead of filling the single (non-filtered) dot with the color `'#9467bd'`, the output SVG has `fill="snow"`. For the case involving the last entry in the domain array, for some reason the data value itself is being passed through rather than a color scale output.

```js
Plot.plot({
  x: { domain: [1, 5] },
  color: {
    domain: ['sun', 'fog', 'drizzle', 'rain', 'snow'],
    range: ['#e7ba52', '#a7a7a7', '#aec7e8', '#1f77b4', '#9467bd']
  },
  marks: [
    Plot.dot(
      [
        {x:1, y:1, z:'sun'}, {x:2, y:1, z:'fog'}, {x:3, y:1, z:'drizzle'},
        {x:4, y:1, z:'rain'}, {x:5, y:1, z:'snow'}
      ].filter(d => d.z === 'snow'),
      { x: 'x', y: 'y', fill: 'z', r: 10 }
    )
  ]
})
```

I believe this is a bug in Plot. In my limited testing, the error goes away when changing the filter condition to include any of the earlier values in the given color domain.

**Comment by mbostock** [comment]
Yes, this looks like a bug at first glance. I’ll investigate. A quick workaround is to use the **filter** transform instead of filtering the data:

![untitled (3)](https://github.com/observablehq/plot/assets/230541/850d1b7c-e597-4b0a-b01d-078b289d23ee)

```js
Plot.plot({
  x: { domain: [1, 5] },
  color: {
    domain: ["sun", "fog", "drizzle", "rain", "snow"],
    range: ["#e7ba52", "#a7a7a7", "#aec7e8", "#1f77b4", "#9467bd"]
  },
  marks: [
    Plot.dot(
      [
        { x: 1, y: 1, z: "sun" },
        { x: 2, y: 1, z: "fog" },
        { x: 3, y: 1, z: "drizzle" },
        { x: 4, y: 1, z: "rain" },
        { x: 5, y: 1, z: "snow" }
      ],
      { filter: (d) => d.z === "snow", x: "x", y: "y", fill: "z", r: 10 }
    )
  ]
})
```

**Comment by mbostock** [comment]
This is not a bug, but a consequence of *snow* being a valid [named CSS color](https://developer.mozilla.org/en-US/docs/Web/CSS/named-color) (`#fffafa`). 😬

In order to opt-out of this behavior, you can either use the **filter** transform as shown above—which means the other values will be visible to Plot when deciding whether to bind the **fill** channel to the *color* scale, and hence it can tell that the *snow* isn’t intended to refer to a literal color—or you can explicitly opt-in to the *color* scale by using a scale override:

![untitled (4)](https://github.com/observablehq/plot/assets/230541/100d0045-8b13-48fb-8c99-98cea7e5d1c4)

```js
Plot.plot({
  x: { domain: [1, 5] },
  color: {
    domain: ["sun", "fog", "drizzle", "rain", "snow"],
    range: ["#e7ba52", "#a7a7a7", "#aec7e8", "#1f77b4", "#9467bd"]
  },
  marks: [
    Plot.dot(
      [
        { x: 1, y: 1, z: "sun" },
        { x: 2, y: 1, z: "fog" },
        { x: 3, y: 1, z: "drizzle" },
        { x: 4, y: 1, z: "rain" },
        { x: 5, y: 1, z: "snow" }
      ].filter((d) => d.z === "snow"),
      { x: "x", y: "y", fill: {value: "z", scale: true}, r: 10 }
    )
  ]
})
```

I think we could make inferChannelScale smarter in this case, such that if you have a *color* scale with an explicit domain, then we don’t consider any channel values that are present in the domain as CSS colors. But that might be overfitting to this particular case, so I’m not sure it’s worth the fix. I’ll retitle this as a feature request since this is the intended behavior.

**Comment by jheer** [comment]
Thanks for the explanation! Beyond passing in CSS color names directly as a string literal option (which is great), I did not realize (nor expect) that values that match CSS color names passed in as *data* would be interpreted as such. I'm not yet seeing why this behavior is desirable/intended.

**Comment by mbostock** [comment]
You can have a channel that supplies literal CSS colors, too:

![untitled (5)](https://github.com/observablehq/plot/assets/230541/d25eb1d9-b7d5-45ed-8d8e-5812905f4d63)

```js
Plot.cellX(d3.ticks(0, 1, 10), {fill: d3.interpolateBlues}).plot()
```

We can’t really say that channels provide “data”—just a column of values. Perhaps we could make an exception here because the *fill* column is specified as a field name of data, but normally we don’t differentiate based on how the data was supplied; we only differentiate based on the values of themselves.

It’s just nice sometimes to be able to provide literal colors and to bypass the *color* scale. And it’s nice that the behavior of the constant option is the consistent with the channel. Normally there’s enough of a signal that it’s clear what is intended—it’s just not in this case because there are some obscure CSS color names, and the channel only provides a single value (*snow*).

I could also see us disabling this behavior for named CSS colors, and only keying off strings that are more obviously colors (such as hexadecimal or rgb(…)). But that might be surprising or undesirable too; e.g., it’s nice sometimes to `return d.value > 10 ? "red" : "black";` from a channel value function to specify literal values.

**Comment by mbostock** [comment]
The workaround I described is implemented at #1595, but I’m not sure we should do it. More thought required. 🤔

**Comment by jheer** [comment]
Thank you for the rapid attention to this issue! Thanks to your comments I can now work around this behavior by using a scale override on fill/stroke channels when my code generates Plot specifications. I don't have a strong opinion on #1595, as other ambiguous cases remain, namely: trying to encode data values that happen to match CSS color names when no explicit domain is provided.

**Comment by mbostock** [comment]
You’re very welcome. Thank you for the feedback! Since there isn’t a strong consensus that #1595 is an improvement, I’m going to close both this issue and the PR, but please let me know if you have further thoughts on what we could improve.
