### ISSUE TITLE
d3 version compatibility issue for 0.6.7

### ISSUE THREAD

**Issue by nobarany** [observablehq/plot#1666]
I'm using the latest d3 (7.8.4) and seems like upgrading to the latest plot (0.6.7) causes this error:
```
✘ [ERROR] No matching export in "node_modules/d3/src/index.js" for import "unixDay"

    node_modules/@observablehq/plot/src/time.js:1:39:
      1 │ import {utcSecond, utcMinute, utcHour, unixDay, utcWeek, utcMonth, utcYear} from "d3";

```

**Comment by mbostock** [comment]
d3 has a transitive dependency on d3-time, so you’ll need to run `yarn upgrade` or equivalent to upgrade your version of d3-time. The version of d3 on npm doesn’t really tell you anything because all of the dependencies are version ranges:

https://github.com/d3/d3/blob/37b1960e0af52d12bc7bbea2ed932ea954c36d14/package.json#L37-L66

**Comment by nobarany** [comment]
Upgrade worked. Thanks much!
