### ISSUE TITLE
Could Plot.auto make the Simpsons cell heatmap?

### ISSUE THREAD

**Issue by tophtucker** [observablehq/plot#1672]
Selecting a bar override on "season" vs "number_in_season" makes a bunch of zero-width, zero-height rects (and a working tooltip with some extraneous intervals): https://observablehq.com/d/58a592d7a3c97fc8

<img src="https://github.com/observablehq/plot/assets/841829/38fd1d36-db73-41b7-88c0-8172b6afd163" width="640">

```js
Plot.auto(simpsons, {x: "season", y: "number_in_season", color: "imdb_rating", mark: "bar"}).plot()
```

I wish it made this:

<img src="https://github.com/observablehq/plot/assets/841829/ab534e23-49e1-4d13-933a-cf95350bb6e6" width="640">

```js
Plot.cell(simpsons, {x: "season", y: "number_in_season", fill: "imdb_rating"}).plot()
```

If there's no reducer / no binning by which to give the rects extent, could we infer that we could treat x and y as discrete and use cell instead? Though maybe that'd be brittle; it'd kinda depend on the numbers being evenly spaced.

**Comment by mbostock** [comment]
I think this is a straight-up bug, not the intended behavior. I believe the code assumes that if we’re using the rect mark, that there’s a color reducer (and hence that *x* and *y* are binned). But that isn’t the case in the provided snippet.

Here are some options that I don’t immediately reject:

1. Choose cell instead of rect as the mark implementation.
2. Ignore the **mark** option and use dot instead.
3. Throw an error explaining that a reducer is required. (I don’t like this one.)
4. Add an implicit color reducer (_median_? _mode_? _first_?) to enable binning.
5. Add an implicit interval option? (But how would we know what interval to use…)

To me (1) choosing cell instead of mark is likely the easiest fix and seems like the place to start. I think it’s this line here, but you have to check whether a colorReduce was specified. (I think we’d still chose cell if a sizeReduce was specified? But the inputs don’t make much sense since the bar mark doesn’t support a size encoding.)

https://github.com/observablehq/plot/blob/16c75f4379df795277626c051065de3e96633687/src/marks/auto.js#L134

I would _not_ introduce a _cell_ **mark** option as @Fil suggested. A big value-add of the auto mark is that the differences between the rect marks are ignorable and in the chart cell we wouldn’t want the user to choose between _cell_ and _bar_ (and _rect_).
