### ISSUE TITLE
Exclude block titles from docs search

### ISSUE THREAD

**Issue by mootari** [observablehq/plot#1787]
Searching for "tip" in the docs gets a lot of false positives because of the "TIP" boxes. Is it possible to exclude titles of custom blocks from the search?

**Comment by Fil** [comment]
The minisearch instance is configurable starting with vitepress >= 1.0.0-beta.5 (https://github.com/vuejs/vitepress/pull/2576).

An alternative approach would be to use a different keyword for these insets (to avoid collisions with important Plot keywords).

However, since the 7 first results of a search for "tip" are what I expect they should be (and in the correct order of priority), I don't think we need to do anything?

<img width="936" alt="Capture d’écran 2023-08-16 à 09 06 30" src="https://github.com/observablehq/plot/assets/7001/ae8f4fec-fe8b-4196-9dc8-7c9d06df2ed4">
