### ISSUE TITLE
possible binning 'sum' reducer bugs

### ISSUE THREAD

**Issue by jonhelfman** [observablehq/plot#1788]
There seems to be a bug or two with the 'sum' reducer when handling an array of zeros:

1. Does a vertical scale labeled 'Frequency' make sense for the 'sum' reducer?
2. For an array of zeros, shouldn't the sum of any bin be zero, making the bar lengths zero and, therefore, hiding the bars?

see https://observablehq.com/@jonhelfman/plot-bin-sum-reducer-bug

**Comment by mbostock** [comment]
> For an array of zeros, shouldn't the sum of any bin be zero, making the bar lengths zero and, therefore, hiding the bars?

If you don’t specify the **y** input channel to the _sum_ reducer, then it defaults to unity, not identity. It’s **x** that defaults to identity here. A more explicit form of what you wrote is:

![untitled (53)](https://github.com/observablehq/plot/assets/230541/553d0f46-7793-44e6-ad6d-05d70bed2731)

```js
Plot.rectY({ length: 10 }, Plot.binX({ y: "count" }, { x: 0 })).plot()
```

In other words, the chart is showing you that you have 10 items in your data, all at **x** = 0.

If you want **y** to be zero also, you’d say:

![untitled (54)](https://github.com/observablehq/plot/assets/230541/0b8b565d-448a-4059-9736-d3358a4def04)

```js
Plot.rectY({ length: 10 }, Plot.binX({ y: "sum" }, { x: 0, y: 0 })).plot()
```

As for the label “frequency” — hopefully that’s now clear given that you were getting a count of the number of elements in your data since you didn’t supply an input value and hence were effectively using *count* instead of *sum*. That label goes away if you switch to doing an actual sum.

![untitled (55)](https://github.com/observablehq/plot/assets/230541/ad54d676-3e97-41c5-aa54-fd6f67b71dca)

```js
Plot.rectY({ length: 10 }, Plot.binX({ y: "sum" }, { x: 0, y: 1 })).plot()
```

**Comment by jonhelfman** [comment]
Ok. Thank you for your response and explanation. Originally, I had tried specifying that y:0, and I also got the second chart that you show above. But this also seems wrong because the bar has a height and, unlike any other type of bar chart, it is centered at the zero mark. If the bar indicates a sum of zeros it should not have a height. For me, the reason becomes clear when the chart is being updated dynamically to show the selection in another chart -- when the selection includes only zeros, bars appear, when it really seems they should be hidden! I need to add explicit code to filter out zeros to get a consistent behavior for this use case.

**Comment by jonhelfman** [comment]
I updated the example here https://observablehq.com/@jonhelfman/plot-bin-sum-reducer-bug to demonstrate the selection use case described above.

Thanks again for your attention!   -jon

**Comment by mbostock** [comment]
> If the bar indicates a sum of zeros it should not have a height.

The issue here is that the domains are degenerate: they are both [0, 0]. So, it’s essentially a divide by zero problem. We have special code that handles this by showing the singular domain value in the middle of the range, and marks that represent extents span the respective axis of the frame.

If you don’t want to see the bars here, you need to prevent the domain from being degenerate. One way to do that is to set a fixed domain like so:

![untitled (56)](https://github.com/observablehq/plot/assets/230541/456f0718-6022-4701-97f1-7ea2d5d005cc)

```js
Plot.plot({
  y: { domain: [0, 1] },
  marks: [Plot.rectY({ length: 10 }, Plot.binX({ y: "sum" }, { x: 0, y: 0 }))]
})
```

You could also accomplish this by having an invisible rule at *y* = 1, or whatever upper value you want to show when you don’t have any data. This avoids having to hard-code the domain.

```js
Plot.plot({
  marks: [
    Plot.ruleY([1], { stroke: null }),
    Plot.rectY({ length: 10 }, Plot.binX({ y: "sum" }, { x: 0, y: 0 }))
  ]
})
```

**Comment by jonhelfman** [comment]
fascinating and brilliant!
Thank you ever so much
--jon
