### ISSUE TITLE
allow native color functions with CSS vars as colors

### ISSUE THREAD

**Issue by ndfnzio** [observablehq/plot#1851]
Closely related to https://github.com/observablehq/plot/issues/765.

It would be great if the `isColor` check supported native color functions with CSS vars inside. Some examples:
- `rgba(255, 0, 0, var(--a))`
- `rgb(var(--rgb))`
- `hsl(240deg 50% var(--l))`
- `hsl(var(--hsl) / 50%)`

Thanks!

**Comment by mbostock** [comment]
Agree. We are too strict in validating colors because we rely on [d3-color](https://github.com/d3/d3-color) which does not support CSS Level 4 https://github.com/d3/d3-color/issues/96 and other modern enhancements to CSS. I think we could be much more lenient here, allowing anything that looks like it might be CSS, including rgba(…), hsl(…), lch(…), oklab(…), without strictly validating or trying to parse the string. (We still need to check against the X11 named colors though!)

**Comment by Fil** [comment]
See also https://github.com/observablehq/plot/pull/1454
