### ISSUE TITLE
Area mark not passing along null value when only specifying "y" channel

### ISSUE THREAD

**Issue by jzavala-gonzalez** [observablehq/plot#1875]
Hi! Thank you for this library. Notebook replicating this issue is at [this link](https://observablehq.com/d/5849aa52b14164d6). I was just using the areaY mark and found that when using null values in the data to signify cutoffs between rendered regions, that the area includes two extraneous points that should have been filtered out. The resulting shape is trapezoidal rather than rectangular. It's hard to notice when data density is high but visible otherwise. One workaround is by specifying both y1 and y2, and including nulls in both when necessary.

**Comment by Fil** [comment]
Can you share an example please?

**Comment by Fil** [comment]
This is due to the implicit stackY transform called by the areaY mark. What happens when a value is NaN or 0 (null being transformed into NaN) is decided here https://github.com/observablehq/plot/blob/main/src/transforms/stack.js#L109

This allows for example [this test](https://github.com/observablehq/plot/blob/main/test/plots/downloads.ts) to work, by making an area show something for isolated dates. It's also explicitly test in integerIntervalAreaZ (#1775).

A different way to address this would be to use a filter transform:
> filter: d => d.y > 10,
