### ISSUE TITLE
tip: true is not working on vue3 ssr 

### ISSUE THREAD

**Issue by xalteropsx** [observablehq/plot#1945]
```
<PlotFigure 
    :options="{
  marks: [
     
      Plot.lineY([
  { Open: 64.501427, High: 65.414284, Low: 64.500000, Close: 64.962860, Volume: 79237200},
  { Open: 64.835716, High: 65.028572, Low: 63.164288, Close: 63.408573, Volume: 111779500},
  { Open: 62.737144, High: 63.000000, Low: 60.337143, Close: 61.264286, Volume: 185403400},
  { Open: 60.462856, High: 62.549999, Low: 59.842857, Close: 62.082859, Volume: 150801000},
  { Open: 62.721428, High: 62.869999, Low: 61.572857, Close: 61.894287, Volume: 106976100}
], {x: 'Open', y: 'High',tip: true}),
  ]

    }"
  ></PlotFigure>

**Comment by Fil** [comment]
What is "PlotFigure" supposed to do? In any case, the problem is probably unavoidable, since the [pointer interaction](https://observablehq.com/plot/interactions/pointer) needs javascript and cannot be serialized to plain svg. It's possible to imagine a re-hydration script that works from the serialized (SSR) version, but to my knowledge this does not exist (even as a prototype) at this point in time. Could be fun to try, though!
