### ISSUE TITLE
Chart with facets: ticks overflow

### ISSUE THREAD

**Issue by Jerboas86** [observablehq/plot#2025]
In charts with facets:
If ticks property is defined without domain property, the axis will overflow.

### Bug reproduction

([see observablehq](https://observablehq.com/d/f13bff9d35f60e45))

### Expected behavior

- no overflow
- domain is derived from ticks

**Comment by Fil** [comment]
can you share the notebook? 🙏

**Comment by Jerboas86** [comment]
> can you share the notebook? 🙏

Sorry for that, it should be public now

**Comment by Fil** [comment]
That's the expected behavior. If you want to derive the domain from the ticks, you can add a mark that will inject the ticks into the channels considered to build the domain. Or better yet, use the axisX mark with explicit ticks:

      Plot.axisX([125, 250, 500, 1000, 2000, 4000, 8000]),

and then you don't need to specify them again in the specification for the *x* scale.

**Comment by Jerboas86** [comment]
the axis of Facet A goes over axis of axis B, how that can be the expected behavior ?

**Comment by Fil** [comment]
"Expected behavior" does not mean that it results in a great chart, only that it's what the code is expected to do.
