### ISSUE TITLE
`areaY` plot does not correctly render discontinuities

### ISSUE THREAD

**Issue by plmrry** [observablehq/plot#2178]
The `Plot.areaY` function does not seem to respect `null` values the same way `Plot.area` does:

https://observablehq.com/@plmrry/area-y-bug

<img width="467" alt="Screenshot 2024-09-26 at 6 37 06 PM" src="https://github.com/user-attachments/assets/80c01c3a-a27b-4641-a585-b03e633cdd62">

**Comment by mbostock** [comment]
The stack transform is likely coercing null to zero. This might be intended… I’ll need to think about this more.

**Comment by mbostock** [comment]
Although this isn’t explicitly documented, this is functioning (at least partly) as intended: the stack transform, like d3-array methods such as d3.sum, ignores null, NaN, and undefined values when computing the extent of each stacked column. The code can be seen here:

https://github.com/observablehq/plot/blob/e0bf09ea4dd537188c1fe11eca169d46bafb4fa8/src/transforms/stack.js#L107-L109

You probably didn’t intend to use the stack transform in this case, and the areaY shorthand probably shouldn’t use the stack transform since it doesn’t make sense in this context. You can fix your code by setting the **y2** channel to opt out of the stack transform:

```js
Plot.plot({
  width,
  height: 200,
  marks: [
    Plot.line(data, { x: (d, i) => i, y: (d) => d }),
    Plot.areaY(data, { y2: Plot.identity, opacity: 0.1 })
  ]
})
```

I’ll make the areaY shorthand do this by default.
