### ISSUE TITLE
Temporal tickFormat for facet reported as invalid if dataset is empty

### ISSUE THREAD

**Issue by mootari** [observablehq/plot#2231]
If a plot defines a temporal `tickFormat` like `%W` for a facet, and the dataset is empty, then rendering the Plot will fail with the error:
> Error: invalid format: %W

Example:
```js
Plot.barY([], {fy: d => d}).plot({fy: {tickFormat: "%W"}})
```
For comparison:
```js
Plot.barY([new Date()], {fy: d => d}).plot({fy: {tickFormat: "%W"}})
```

**Comment by Fil** [comment]
Same issue with `Plot.barY([]).plot({ y: { tickFormat: "%W" } })`

Not that there is no possibility to specify that the values are dates by setting the scale’s *type* ("utc"), since it must be "band".

A work-around for now is to say `tickFormat: d3.utcFormat("%W")`.

**Comment by mbostock** [comment]
The relevant bit of code is:

https://github.com/observablehq/plot/blob/700c6eef9c179fa5bef6bf2a4d5b6a74591d8951/src/marks/axis.js#L677-L678

If the scale domain is empty, I guess we could either ignore the tick format entirely (since it won’t be used to display anything anyway), or we could look at the string and try to guess whether it’s a date format or a number format. Probably the way to do that is to parse it as a number format first, because number formats are stricter than date formats, and only fallback to a date format if the number format fails. But ignoring the tick format if the scale domain is empty seems a lot simpler.

**Comment by mbostock** [comment]
It’s even more interesting in @Fil’s example because the scale domain isn’t empty _per se_: it’s defaulting to a linear scale, so the domain is [NaN, NaN] rather than []. Maybe also we should default to an ordinal scale when the domain is empty?

**Comment by mbostock** [comment]
The error here is expected:

```js
Plot.barY([]).plot({y: {tickFormat: "%W"}})
```

With barY, the bar starts at 0 and ends at _y_ by default, so we know that the _y_ scale is _linear_ even though there’s no data and hence the `%W` tick format is invalid. But the equivalent example with barX  or setting the _x_ tickFormat shouldn’t error, either.
