### ISSUE TITLE
Plot.stack(X/Y) is often implicit, so should we use/consider it?

### ISSUE THREAD

**Issue by ericemc3** [observablehq/plot#390]
It seems to me that stacking with Plot is mostly implicit, and many examples using `Plot.stack` continue to work identically if you remove it :

https://observablehq.com/@observablehq/plot-stack?collection=@observablehq/plot

`Plot.areaY(unemployment, Plot.stackY({x: "date", y: "unemployed", fill: "industry", title: "industry"}))`

can thus be safely replaced by :
`Plot.areaY(unemployment, {x: "date", y: "unemployed", fill: "industry", title: "industry"})`

Only in combination with a `Plot.text` does `Plot.stack` seem to be necessary, but I haven't quite understood why..., or when a variant of the `Plot.stackY1` type is needed.

Anything that can simplify the writing is of course welcome!

PS: Plot is a great library, very intellectually stimulating, and the 21 beautifully written articles in the https://observablehq.com/collection/@observablehq/plot collection should be read by all data scientists!

**Comment by mbostock** [comment]
See the [README](https://github.com/observablehq/plot/blob/main/README.md) for a description of how the implicit stack transform works. Some of the examples in the tutorials predate the addition of the implicit stack transform and could be updated to use it instead of applying the stack transform explicitly, though in other cases it is desirable to have it explicit either for clarity or because it is needed (e.g., for Plot.text which does not have an implicit stack transform, or because we want Plot.stackY1 instead of Plot.stackY). See #348 for details.
