### ISSUE TITLE
reduce: proportion for counts

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#399]
As @yurivish remarks in https://observablehq.com/d/0d9e55233e524500 the "proportion" reducer doesn't get an automatic label if we don't pass _x_, and crashes if we pass it a string channel _x_ (since the sum of strings is 0).

**Comment by yurivish** [comment]
With the "proportion-count" approach we would also need "proportion-facet-count" and things start feeling a bit combinatorial. Though maybe we don't need combinations other than those two.

As far as implementation I was imagining a switch on the type of the first non-`null` non`undefined` element, then computing either the sum or the number of elements in `x`, similarly to how type inference is talked about in the documentation:

> For simplicity’s sake, Plot assumes that data is consistently typed; type inference is based solely on the first non-null, non-undefined value.

**Comment by mbostock** [comment]
In the same way that the _sum_ reducer “crashes” (i.e. produces NaN output) when given non-numeric input values to sum, I think it’s desirable that the _proportion_ reducer behave the same way when given input values that are non-numeric. In other words, just as the _sum_ reducer does not (and should not) treat all the input values as unity if the input values are non-numeric, nor should the _proportion_ reducer accept non-numeric values when an input is specified. My recommendation in the motivating example is simply to remove the `x: 'key'` input to the _proportion_ reducer:

```js
Plot.stackX(
  Plot.groupZ(
    { 
      x: 'proportion', 
      text: 'first'
    },
    {
      fill: 'key',
      text: 'key',
      order: 'value',
      insetRight: 1
    }
  )
)
```

Regarding the automatic label, you shouldn’t need to change the semantics of the operation (i.e., switch from an unweighted to a weighted proportion) in order to pass through the label. There’s competition for the implicit label here: there’s the reducer (here _proportion_, which has the implicit label “Frequency”) and the group definition (here using the “key” column from the _fill_ channel). I don’t think it’s appropriate to label the _x_-axis “key” here, since it represents frequency (i.e., the proportion), not the key. The data is grouped by key, but that encoding only exists in the fill and labels for the bars.

So, my vote is to close this issue (but please continue the discussion if you’re not convinced) and #410. But I’m going to open a separate issue to throw an error when you try to pass a non-numeric channel to something that requires numeric input, such as the _proportion_ and _sum_ reducer, so that Plot makes clearer what’s going wrong.

Ref. https://github.com/observablehq/plot/pull/410#issuecomment-890577750
