### ISSUE TITLE
Can't set unknown domain in colour scale

### ISSUE THREAD

**Issue by rossburton** [observablehq/plot#446]
I'm using the color scale with explicit domain/range to associate status names with colours:

```
  color: {
    type: "categorical",
    domain: ["success", "failed"],
    range: ["green", "red"]
  },
```
But status names I forgot to list come out invisible.  A way of setting the `unknown()` value would be useful, it looks like it is hardcoded to `undefined` at https://github.com/observablehq/plot/blob/068f8d8125a910ee1a528c8b299a79c27ca1a9a5/src/scales/ordinal.js#L206.

**Comment by mbostock** [comment]
Anything outside the domain will not be plotted; we need the “other” transform for this use case.

**Comment by zanarmstrong** [comment]
I ran into something that seems similar related to NAs when plotting height / weight  the Olympics dataset. Example [here](https://observablehq.com/@zanarmstrong/thinking-about-nas-in-a-numeric-column).

**Comment by Fil** [comment]
Another use-case (very similar to Zan's) can be found in https://observablehq.com/@rcatlord/spine-charts; for some of the areas (try "Rother" in the select), the value comes in as "NA" instead of a number, and the x axis switches to a categorical scale.

<img width="659" alt="Capture d’écran 2021-09-14 à 09 03 15" src="https://user-images.githubusercontent.com/7001/133210888-d99ce3e5-7d08-4f88-a0da-5957028274ed.png">

**Comment by Fil** [comment]
With this feature:

* In Zan's example the N/A can be shown by applying
~~~
  x: { unknown: 45 },
  y: { unknown: 10 }
~~~

* In rcatlord's example, the fix is a bit more complicated, since we need to coerce the scale to be quantitative:
~~~
x: {
  axis: "top",
  label: null,
  type: "linear",
  unknown: 650
}
~~~
