### ISSUE TITLE
Format dates and numbers in title and text

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#476]
Not sure if applies is only to titles or more generally for all dates when coercing them to strings, but we'd want to avoid this:

<img width="326" alt="Capture d’écran 2021-08-03 à 13 31 32" src="https://user-images.githubusercontent.com/7001/128008545-47a262b7-638b-427c-a7eb-1b577b66a4c8.png">

when we have e.g.:
`Plot.dot(data, { x: "date", y: "count", title: "date" })`

**Comment by mbostock** [comment]
Yeah, I think we could have an implicit formatIsoDate format here, if you give the *title* channel temporal data. Similar to the implicit tick format for ordinal axes with temporal domains:

https://github.com/observablehq/plot/blob/4b8b8219490ad17d940a0017d6f9167d4b1bbf7d/src/axis.js#L199-L204

**Comment by Fil** [comment]
Now I want to have a generic titleFormat option available in all marks; the default might be
d => (d instanceof Date) ? d.toISOString() : `${d}`;

It would be particularly useful when the value is a reduction (for example title: "proportion-facet"), and we want to express it as a well-behaved string such as "33.3% of bananas".

**Comment by mbostock** [comment]
formatIsoDate as I proposed only truncates the time for dates that are exactly UTC midnight, so its output is unambiguous. (It’s the shortest equivalent ISO 8601 UTC form.) It is biased towards UTC but that is intentional; we to encourage people to use UTC for dates without times because they will display consistently in different time zones.

I use the wrapper technique sometimes:

```js
(f => d => f(d))(d3.utcFormat(…))
```

Maybe we could have a helper? We have a couple helpers already…

https://github.com/observablehq/plot/blob/main/src/format.js

**Comment by mbostock** [comment]
Expanded the scope of this a bit because it should probably encompass the text channel as well, and also handle numeric channels with better default formatting.

**Comment by mbostock** [comment]
Bumping this because I felt this pain today. 😄
