### ISSUE TITLE
Text in facets

### ISSUE THREAD

**Issue by irenedelatorre** [observablehq/plot#514]
When I use facets and include a Text mark, all the items in the array are plotted instead of filtering by the faceting variable. I'm not sure if this is because of how I'm adding the text mark, or if it's a bug. I haven't seen an example of Plot with a facet and annotations that change position and value either.

I've added an example in [observablehq.com/d/a4546964387cf1c1](observablehq.com/d/a4546964387cf1c1
) 

![image](https://user-images.githubusercontent.com/14239920/130228793-deb676f5-351f-4b29-b08a-b8362800755e.png)

Thanks, 
Irene

**Comment by mbostock** [comment]
[Faceting](https://github.com/observablehq/plot/blob/v0.1.0/README.md#facet-options) currently requires that the data of the faceted mark is strictly equal to (`===`) the facet data. Otherwise, the mark will be repeated across all facets. It looks like you have different data for your faceted mark here (["test 1", "test 2", …]).

You can workaround this limitation by using the [select transform](https://github.com/observablehq/plot/blob/v0.1.0/README.md#select) (e.g., Plot.selectFirst) to give the faceted mark the same data as the facet (here, penguins), and then pull out a specific datum for each facet to label.

Plot 0.2 will introduce a [*facet* option](https://github.com/observablehq/plot/blob/main/CHANGELOG.md) that will allow you to turn faceting on explicitly for a given mark. However in this case you will still be required to give the faceted mark data that is parallel to the facet data (the same length and order) so that Plot can correctly assign the data to each facet. So, if you only want to label certain points in your scatterplot on each facet, you may need the select transform anyway.

If you’d like us to look at your notebook, please publish (unlisted) so we can see. My response above is speculative but hopefully it’s helpful! 😄

**Comment by mbostock** [comment]
(Please reply to this issue, even though it’s closed, if you’d like further assistance. If this does turn out to be a bug, I will reopen.)

**Comment by Fil** [comment]
I've sent you a suggestion https://observablehq.com/compare/a4546964387cf1c1...87d393e4f6081444
We hope to make faceted labels easier in the future (see #501).

**Comment by mbostock** [comment]
To add to Fil’s suggestion, here is an example of using select:

```js
Plot.text(data, Plot.selectMaxY({x: "flipper_length_mm", y: "body_mass_g", text: "species"}))
```

**Comment by irenedelatorre** [comment]
Hi Mike and Phil, 
My question is then how can you use `select` if you want only specific points?
You might not be interested in the max or min value but, for example, the value in one specific date, and that input might depend on the facet (ie. add dates of lockdowns for each country in facets visualizing coronavirus rates).
Is there a way when you use `select` to get the key of the facet you're in and use it for filtering for example? That could help to add annotations without having to repeat them in each of the small multiples.

My notebook is unlisted, although it's just an example with dummy annotations 😅

**Comment by mbostock** [comment]
> My question is then how can you use select if you want only specific points?

You can approach it as filtering: imagine that all of your data points have an associated label, but that most of the time that label is the empty string. See the *nyt_display* column here:

https://observablehq.com/@observablehq/plot-link

**Comment by irenedelatorre** [comment]
Oh, so you pass it through the whole array included in the facet. I hadn't thought about that, thank you!
