### ISSUE TITLE
Plot.circle() instead of Plot.dot()

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#519]
When explaining marks, I refer to Plot.dot() as a circle. So I wonder why Plot.dot() is preferable to Plot.circle()?

Apart from a breaking change:
- the default radius makes a Plot.dot() a circle
- the generated SVG element is a circle
- a dot seems a special case of the circle not vice versa

**Comment by mbostock** [comment]
A few reasons…

* Small circles are often referred to as “dots”. Plot dots tend to be small.
* “Dot” is shorter to spell and to say than “circle”.
* In the future Plot.dot will support multiple symbols, not just circles. #41 
* Plot marks are partly named after common associated chart types (e.g., “dot plot”).
* Plot marks are not generally named after their implementation (e.g., both bar produce rects, line produces paths).

We didn’t use the name Plot.scatter because that tends to imply two-dimensional dots, and Plot.dot can be used in one-dimensional charts. Also “dot” is shorter than “scatter”.

In any case we wouldn’t change the name and break backwards compatibility, though it’s possible we might have an alias in the future. We can consider this as part of #41 (which might introduce a Plot.symbol mark).

**Comment by EE2dev** [comment]
Thanks for the explanation! And to be honest, I can't argue reason #3
