### ISSUE TITLE
Don’t round band and point scales by default, or at least for high-cardinality domains?

### ISSUE THREAD

**Issue by yurivish** [observablehq/plot#547]
Plot [rounds ordinal scales](https://github.com/observablehq/plot/blob/0bbf70e482916db92ae1dc78e9b9b3e9e6f40911/src/scales.js#L56) by default, which results in extra padding at the ends of an ordinal axis. 

![image](https://user-images.githubusercontent.com/114388/134226376-4a04c723-1e4b-4f01-aa51-c2cc631f7a22.png)

The amount of padding at the top of a chart depends on the number of datapoints, which you can see in [this example](https://observablehq.com/d/cfd85fdacf14922b).

The rounding heuristic is nice since it ensures a round number of pixels per ordinal value. Since the height of the chart does not adjust to compensate, however, this introduces potentially large gaps in the resulting plot (so much that I initially thought this was a bug, not a feature).

One idea for a fix would be to enable the rounding heuristic only if a plot height is not specified by the user, and adjust the height to ensure no unwanted padding.

Another idea would be a tolerance to allow only up to some fixed amount of padding, for nicer behavior in the case of fixed-size charts. Width is always fixed, so this would help reduce gaps in the case of an ordinal x axis.

Also, Fil points out that on retina screens you only need half-rounding :)

(Thanks to Fil for insight on the rounding heuristic + discussion on Slack.)

**Comment by Fil** [comment]
This was reported to me quite independently on Friday too… I think the simplest way to solve it is to default _round_ to false for ordinal scales—at least on y. https://github.com/observablehq/plot/blob/main/src/scales.js#L52

**Comment by mbostock** [comment]
This is primarily a problem for high-ish-cardinality domains. If the _y_-domain has 60 or fewer elements, you won’t reach the cap on the maximum default height, so there’s no wasted space introduced by rounding:

https://github.com/observablehq/plot/blob/4f73ee5fbbfcdd386bfaccbc2bbaae5ebc10a524/src/plot.js#L149

But once you’re over 60, rounding starts to waste space. The problem goes away again when the domain has 240-ish or more elements, because then the step size drops below 5, changing the autoround heuristic:

https://github.com/observablehq/plot/blob/4f73ee5fbbfcdd386bfaccbc2bbaae5ebc10a524/src/scales.js#L71

So, a quick fix would be to update the autoround heuristic so that it’s false if the domain has more than 60 elements. That way it’s consistent with the default height cap, and you’re less likely to run into situations where the wasted space due to rounding is many multiples of the scale’s step size.

Alternatively, we could have a heuristic that is based on the wasted space due to rounding more explicitly, e.g., to only turn on rounding by default if it will waste fewer than 20 pixels.
