### ISSUE TITLE
Line with dot

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#628]
It’d be nice to have a Line+Dot as a built-in primitive, rather than needing a separate Line and Dot mark. Mainly because if you have a multi-series line, you want the dots to be z-interleaved with the lines, rather than drawing all the dots on top of all the lines. Also it’s nice because you don’t have to repeat yourself (and transfer the line’s stroke to the dot’s fill).

**Comment by Fil** [comment]
Reminds me of https://github.com/d3/d3-shape/pull/162 :)

**Comment by mbostock** [comment]
Yes. Perhaps Plot could apply the requested curve (such as linear) and then append the result of curvePoints to the generated path string. (In the case I described, I wanted curveLinear + curvePoints, together.)

**Comment by Fil** [comment]
If we create a single curve that does line+dots, we can stroke it
![untitled (2)](https://user-images.githubusercontent.com/7001/147871012-0f774a05-0b6f-4abd-9175-aa9766bd5bf0.png)

we can also fill it (if we're careful to run the path forward then backward, so that only the dots are fillable).
https://observablehq.com/@observablehq/plot-line-and-dots-628
![untitled (3)](https://user-images.githubusercontent.com/7001/147871018-2acad688-00cf-4243-9e1a-13ad300efabd.png)

However the stroke of the line appears above the fill of the dots, which is not great. Using paint-order: stroke reverses that but merges the dots—it doesn't look nice:
![untitled (4)](https://user-images.githubusercontent.com/7001/147871026-c8e35720-23c0-4572-83c0-a79e13f46a0e.png)

The following combination (which in my view is the nicest-looking) will still need to combine two separate paths:
![untitled (5)](https://user-images.githubusercontent.com/7001/147871038-84c4a086-110c-4f91-83c9-7447780c458b.png)

It's feasible to bake this into the line mark by adding a *r* option, but it's such a complication (https://github.com/observablehq/plot/pull/646), that I don't think we should do it.

demo https://observablehq.com/@observablehq/plot-line-and-dots-628
