### ISSUE TITLE
Get bandwidth for band scale

### ISSUE THREAD

**Issue by RLesser** [observablehq/plot#741]
I might be missing something, but it seems that there's no simple way to get the bandwidth used by a band scale. I'm trying to align additional elements to the center of each band, and currently it involves more math than when a band scale is used in D3.

It could be added as a field within here:
<img width="386" alt="Screen Shot 2022-02-08 at 9 29 14 PM" src="https://user-images.githubusercontent.com/12756127/153110469-42efea0b-0530-474f-b6ea-e73cf842320a.png">

**Comment by mbostock** [comment]
Yes, we should expose the bandwidth and step. 👍

**Comment by Fil** [comment]
My concern is we'll be exposing them, but they won't be considered as inputs to a new scale, so then someone who tries to build a scale from this description might wonder why it "doesn't work" when they change the values.

Would it be a good idea to show this in some way? By exposing them as info_bandwidth or info_step?

Note that apply() and invert() are already "informative" and not "inputs", so maybe I'm just too cautious.

**Comment by mbostock** [comment]
I think it’s okay to expose them event though they are only informational.

**Comment by dgrcode** [comment]
Where can I find some documentation about the API?

I was looking at [this](https://observablehq.com/@observablehq/dual-axis-bar-line-chart) dual-axis bar-line example, and theres a function being used as item in the marks array property, like this:

```js
Plot.plot({
  marks: [
    Plot.barY(data, { x: "year", y: "sales", fill: "#ccc" }),

    (_, { x }, __, dimensions) =>
      Plot.plot({
        // some stuff
      })
  ],

  // some stuff
})
```

The example mentions
> The first experiment uses the internal API and uses the x scale and the dimensions intended for normal marks

Is the internal API documented? if it isn't, what are the files you'd point me to so I can learn more about how to use it?

**Comment by Fil** [comment]
The marks receive the following arguments to their render function, which is called once for each facet:
index, scales, channels, dimensions, context
for example: https://github.com/observablehq/plot/blob/main/src/marks/area.js#L46

* _index_ is an array of indices (into the channels) that we want to render
* _scales_ is an object with keys corresponding to the scales names (x, etc) and values corresponding to the scaling functions
* _channels_ contains the *scaled and transformed* values for each channel
* _dimensions_ give the width, height etc, of the facet
* _context_ indicates the document context to use if we want to create a document fragment (a svg:g node, for instance)

This is not documented because we might still want to change it before version 1.0.

**Comment by dgrcode** [comment]
Awesome, thanks for the info! :)
