### ISSUE TITLE
Voronoi mark

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#812]

**Comment by Fil** [comment]
Here are a few explorations of a delaunay/voronoi plugin, written as a transform. However this should probably be done as initializers/layouts (#801) since the x and y dimensions are not separable (Delaunay/Voronoi being based on the euclidian distance on the plane).

https://observablehq.com/@observablehq/plot-delaunay-voronoi-mark-812
![untitled (22)](https://user-images.githubusercontent.com/7001/159007847-2bde453b-4c01-41eb-b242-1ebcaae2507b.png)
![untitled (23)](https://user-images.githubusercontent.com/7001/159007837-48982757-7ecb-43e0-b704-9b71f10f6688.png)
![untitled (24)](https://user-images.githubusercontent.com/7001/159007832-028bf72f-c890-4dbb-850e-13a9d434bad5.png)
![untitled (25)](https://user-images.githubusercontent.com/7001/159007923-a3699950-923d-4e07-9947-f090fc6375a0.png)

**Comment by Fil** [comment]
Here's the same exploration, but this time as an initializer:
https://observablehq.com/@observablehq/plot-delaunay-layout-812

My current feedback with custom initializers and transforms:
- dealing with z/stroke/fill is very tedious.
- this initializer doesn't compose with the others because Plot.composeInitializers is not exported (but it's just a matter of exporting it as we do for Plot.transform).
