### ISSUE TITLE
Add fx and fy options for marks, to set the facet directly?

### ISSUE THREAD

**Issue by skybrian** [observablehq/plot#875]
Marks have a *stroke* option that lets you set the color directly, bypassing color scales. Could Plot do the same for facets?

Suppose there were *fx* and *fy* options for marks, which can be used to set to the facet where you put the mark.

For example, to plot two graphs side by side:
```
Plot.plot({ 
    marks: [
      Plot.lineY(left, {x: (d, i) => i, stroke: "blue", fx: 0}),
      Plot.lineY(right, {x: (d, i) => i, stroke: "green", fx: 1})
    ],
})
```

The semantics might be similar to stroke, where you could either set it to be the same for all marks in that line, or supply a function to fx and fy to decide where to put the mark. If you don't say, the default might be to duplicate the mark in all facets along that dimension.

(This might not be true faceting, but it would be an easy way to plot small multiples.)

**Comment by mbostock** [comment]
I don’t think we would support this. Feels too low-level.

**Comment by skybrian** [comment]
A higher-level alternative might be to make channels of abstract values that are passed through the fx and fy scales, similar to the other scales.

That way the same array doesn't have to be passed in twice, for the mark and for facet's data option.

**Comment by mbostock** [comment]
I just don’t see us doing this. Plot uses facets for partitioning a dataset, and this API proposal feels like something else.

**Comment by Fil** [comment]
Closing for now: it seems like the discussion https://github.com/observablehq/plot/discussions/874 is about the same issue, and has examples. I've added another example with a (tricky) transform from "facet names" to data.

WRT the comment "the same array doesn't have to be passed in twice", did you see that you can use `facet: true` to facet a mark which doesn't use the same _data_? (It's not entirely solving the issue, because it must be a data with the same cardinality & indexation scheme.)
