### ISSUE TITLE
Dodge error message for non-dodgeable marks could be improved

### ISSUE THREAD

**Issue by yurivish** [observablehq/plot#918]
Dodging a mark for which dodging does not make sense currently throws an error mentioning bandwidth, which can be confusing as the error message does not seem reference objects that the user has direct control over.

https://observablehq.com/d/288a885fcd660a43

<img width="721" alt="image" src="https://user-images.githubusercontent.com/114388/172458752-42822838-3fb1-4cb0-8713-284ecbda474b.png">

**Comment by mbostock** [comment]
The issue here is that the tickX mark assumes that if there is a _y_ channel, that it is associated with a _band_ scale. That’s not the case here because the _y_ channel was constructed by the dodge initializer (and the Plot has no other _y_ scale). We probably want to treat the bandwidth as zero in this case.
