### ISSUE TITLE
regression in Plot.textX?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#961]
See https://talk.observablehq.com/t/plot-text-is-not-showing-up/6758

It was working in 0.4.3, not in 0.5.1.

=> checked by adding a cell with `Plot = require("@observablehq/plot@0.4.3")`

**Comment by mbostock** [comment]
Minimal reproduction https://observablehq.com/d/a943330c90329461

**Comment by mbostock** [comment]
The issue here is that that the _interval_ option for Plot.textX is being used incorrectly; for Plot.textX, the _interval_ option affects the _y_ channel. Pairing a temporal interval with a nominal channel results in undefined values and hence no displayed data. Plot.textY should be used here instead.
