### ISSUE TITLE
Plot.blurX?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#968]
`Plot.blurX({k, ...options}) `would be an alias of `Plot.mapX(data => d3.blur(data, k), options)`. Same for `Plot.blurY`.

https://observablehq.com/@fil/using-d3-blur-with-plot

**Comment by mbostock** [comment]
Don’t we already have this in a sense with Plot.windowX and Plot.windowY? Why would you use Plot.blur instead of Plot.window?

**Comment by Fil** [comment]
Because blurring doesn't vacate the series' edges.

**Comment by mbostock** [comment]
> Because blurring doesn't vacate the series' edges.

True, but couldn’t that be solved generally with the window transform by having the window (optionally) automatically reduce in size on the start and end?

**Comment by Fil** [comment]
This would not work when a series' length is smaller than the window length. (Also, fractional radius!)

**Comment by mbostock** [comment]
> This would not work when a series' length is smaller than the window length. (Also, fractional radius!)

Sure it would; it would just mean that the same window (the entire series) would be used for all values. It would also be possible to support fractional window sizes, but that would (probably?) only make sense for certain reducers (e.g., sum and mean, but not min and max). It’s already possible to implement this using custom reducers.

For me the distinction with blur is that blur is a (Gaussian) weighted moving average. We haven’t implemented any weighted moving averages yet but it is a nice feature. Specifically [exponential moving averages](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average) are common in financial analysis.

I’d also guess that it’s more efficient to re-implement d3.blur rather than call it directly when implementing a reducer (since we want to read from S and write to T), but performance is not the highest priority.

**Comment by Fil** [comment]
Closing because #990 addresses the issue in a more generic way—one can always use Plot.map + d3.blur if they prefer these maths.
